[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ndlar-caf-display"
version = "0.1.5"
authors = [
    { name = "Linda Cremonesi", email = "l.cremonesi@imperial.ac.uk" },
    { name = "Charlotte Knight", email = "charlotte.knight@imperial.ac.uk" },
]
description = "A tool to create event displays of DUNE's NDLAr from flat CAFs."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib",
    "numpy",
    "uproot",
    "awkward"
]
license = "Apache-2.0"
license-files = ["LICENCE"]

[project.scripts]
ndlar-caf-display = "ndlar_caf_display:cli.main"